name: Linting

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true


jobs:
  lint:
    uses: cap-js/.github/.github/workflows/lint.yml@d7f6729c11a3aff1d1e2704df8d1ac47bb2fd927 # main
    secrets: inherit
